// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FirstWebApp.Models.EF_Models;

public partial class Course
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string ImagePath { get; set; }

    public string Author { get; set; }

    public string Email { get; set; }

    public float Rating { get; set; }

    public decimal FullPriceAmount { get; set; }

    public string FullPriceCurrency { get; set; }

    public decimal CurrentPriceAmount { get; set; }

    public string CurrentPriceCurrency { get; set; }

    public virtual ICollection<Lesson> Lessons { get; set; } = new List<Lesson>();
}