// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using FirstWebApp.Models.ValueTypes;
using System;
using System.Collections.Generic;

namespace FirstWebApp.Models.EF_Models;

public partial class Course
{

    public Course(string title, string author)
    {
        if(string.IsNullOrEmpty(title))
        {
            throw new ArgumentNullException("The title must be inserted!");
        }

        if (string.IsNullOrEmpty(author)) {
            throw new ArgumentNullException("The course must have an author");
        }

        Title = title;
        Author = author;
    }

    public int Id { get; private set; }

    public string Title { get; private set; }

    public string Description { get;  private set; }

    public string ImagePath { get; private set; }

    public string Author { get; private set; }

    public string Email { get; private set; }

    public float Rating { get; private set; }

    public Money FullPrice { get; private set; }

    public Money CurrentPrice { get; private set; }

    public void ChangeTitle(string title)
    {
        if (string.IsNullOrEmpty(title))
        {
            throw new ArgumentNullException("The title must be set");
        }
        Title = title;
    }

    public void ChangePrice(Money newFullPrice, Money newDiscountPrice)
    {
        if(newFullPrice == null || newDiscountPrice == null)
        {
            throw new ArgumentNullException("New priceses cannot be null");
        }
        if(newFullPrice.Currency != newDiscountPrice.Currency)
        {
            throw new ArgumentException("Currencies does not match");
        }
        if(newFullPrice.Amount < newDiscountPrice.Amount)
        {
            throw new ArgumentException("Discount price cannot be bigger than Full Price");
        }

        FullPrice = newFullPrice;
        CurrentPrice = newDiscountPrice;
    }

    public virtual ICollection<Lesson> Lessons { get; private set; } = new List<Lesson>();
}