// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FirstWebApp.Models.EF_Models;

public partial class FirstWebAppDBContext : DbContext
{
    public FirstWebAppDBContext(DbContextOptions<FirstWebAppDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Lesson> Lessons { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Course>(entity =>
        {
            entity.HasNoKey();

            entity.Property(e => e.Author)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CurrentPriceAmount)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Courses_CurrentPrice_Amount")
                .HasColumnType("numeric(18, 5)")
                .HasColumnName("CurrentPrice_Amount");
            entity.Property(e => e.CurrentPriceCurrency)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasDefaultValue("EUR")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Courses_CurrentPrice_Currency")
                .HasColumnName("CurrentPrice_Currency");
            entity.Property(e => e.Description)
                .HasMaxLength(4000)
                .IsUnicode(false);
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FullPriceAmount)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Courses_FullPrice_Amount")
                .HasColumnType("numeric(18, 5)")
                .HasColumnName("FullPrice_Amount");
            entity.Property(e => e.FullPriceCurrency)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasDefaultValue("EUR")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Courses_FullPrice_Currency")
                .HasColumnName("FullPrice_Currency");
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.Property(e => e.ImagePath)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Rating).HasAnnotation("Relational:DefaultConstraintName", "DF_Courses_Rating");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Lesson>(entity =>
        {
            entity.HasNoKey();

            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.Duration)
                .HasMaxLength(8)
                .IsUnicode(false)
                .HasDefaultValue("00:00:00")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Lesson_Duration");
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}